project:
  type: website

website:
  title: "jueun bona lee"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - icon: instagram
        href: https://www.instagram.com/itsbonabehind/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

